[package]
name = "minilauncher"
version = "0.1.0"
edition = "2024"

[dependencies]
anstyle = "1.0.13"
clap = { version = "4.5.54", features = ["derive"] }
dirs-next = "2.0.0"
env_logger = "0.11.8"
hex_color = { version = "3.0.0", features = ["serde"] }
log = "0.4.29"
nix = { version = "0.30.1", features = ["user"] }
notify-debouncer-full = "0.6.0"
nucleo-matcher = "0.3.1"
paste = "1"
rust-ini = "0.21.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
slint = "1.14.1"
strip-ansi-escapes = "0.2.1"
sys-locale = "0.3.2"
toml = "0.9.10"
unidecode = "0.3.0"

[build-dependencies]
slint-build = "1.14.1"

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
