[package]
name = "minilauncher"
version = "0.1.0"
edition = "2024"

[dependencies]
anstyle = "1.0.13"
clap = { version = "4.5.54", features = ["derive"] }
dirs-next = "2.0.0"
nucleo-matcher = "0.3.1"
rkyv = "0.8.13"
slint = "1.14.1"
sys-locale = "0.3.2"
unidecode = "0.3.0"

[build-dependencies]
slint-build = "1.14.1"

# Optimize dependencies only in development builds
[profile.dev.package."*"]
opt-level = 3
codegen-units = 1

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
