import { LauncherState, LauncherColors } from "state.slint";

// Main input component
export component LauncherInput inherits Rectangle {
    init => {
        input.focus();
    }

    // Basic styling
    border-radius: 8px;
    border-width: 1px;
    border-color: LauncherColors.border;
    height: 40px;
    clip: true;

    // Placeholder underlay
    Text {
        horizontal-alignment: TextHorizontalAlignment.left;
        text: "Enter a command...";
        color: LauncherColors.border;
        x: parent.x + 5px; // left padding
        width: parent.width - 10px;
        visible: input.text.is-empty;
    }

    function select-next() {
        if LauncherState.selected_index < LauncherState.entries.length - 1 {
            LauncherState.selected_index += 1;
        }
    }
    function select-previous() {
        if LauncherState.selected_index > 0 {
            LauncherState.selected_index = LauncherState.selected_index - 1;
        }
    }

    input := TextInput {
        // Styling
        color: LauncherColors.text;
        text: "";
        x: parent.x + 5px; // left padding
        width: parent.width - 10px;
        vertical-alignment: TextVerticalAlignment.center;

        // Update entries on text change
        edited() => {
            LauncherState.update_entries(self.text);

            // Adjust selected index if out of bounds
            if LauncherState.entries.length == 0 {
                LauncherState.selected_index = 0;
            } else if LauncherState.selected_index >= LauncherState.entries.length {
                LauncherState.selected_index = LauncherState.entries.length - 1;
            }
        }

        // Run command on enter
        accepted() => {
            if LauncherState.entries.length > 0 {
                let selected_entry = LauncherState.entries[LauncherState.selected_index];
                LauncherState.run_command(selected_entry.name);
                input.text = "";
                LauncherState.selected_index = 0;
            }
        }

        // Handle arrow keys
        key-pressed(event) => {
            if event.text == Key.UpArrow {
                select-previous();
                return accept;
            } else if event.text == Key.DownArrow {
                select-next();
                return accept;
            } else if event.text == Key.Escape {
                LauncherState.hide();
                return accept;
            } else if event.modifiers.control && event.text == "j" {
                select-next();
            } else if event.modifiers.control && event.text == "k" {
                select-previous();
            }
            reject
        }
    }
}
