import { LauncherState } from "state.slint";
import { LauncherColors } from "colors.slint";
import { LauncherConfig } from "config.slint";

// Main input component
export component LauncherInput inherits Rectangle {
    forward-focus: input;

    height: LauncherConfig.font-size + LauncherConfig.padding * 3;
    clip: true;

    // Placeholder underlay
    Text {
        horizontal-alignment: left;
        text: "Enter a command...";
        color: LauncherColors.border;
        x: parent.x;
        width: parent.width;
        visible: input.text.is-empty;

        animate color { duration: LauncherConfig.animation; }
    }

    function select-next() {
        if LauncherState.selected_index < LauncherState.entries.length - 1 {
            LauncherState.selected_index += 1;
        }
    }
    function select-previous() {
        if LauncherState.selected_index > 0 {
            LauncherState.selected_index = LauncherState.selected_index - 1;
        }
    }

    input := TextInput {
        // Styling
        color: LauncherColors.text;
        text: "";
        x: parent.x;
        width: parent.width;
        vertical-alignment: center;

        animate color { duration: LauncherConfig.animation; }

        // Update entries on text change
        edited() => {
            LauncherState.update_entries(self.text);

            // Adjust selected index if out of bounds
            if LauncherState.entries.length == 0 {
                LauncherState.selected_index = 0;
            } else if LauncherState.selected_index >= LauncherState.entries.length {
                LauncherState.selected_index = LauncherState.entries.length - 1;
            }
        }

        // Run command on enter
        accepted() => {
            if LauncherState.entries.length > 0 {
                let selected_entry = LauncherState.entries[LauncherState.selected_index];
                LauncherState.run_command(selected_entry.name);
                input.text = "";
                LauncherState.selected_index = 0;
            }
        }

        // Handle arrow keys
        key-pressed(event) => {
            if event.text == Key.UpArrow {
                select-previous();
                return accept;
            } else if event.text == Key.DownArrow || event.text == Key.RightArrow {
                select-next();
                return accept;
            } else if event.text == Key.Escape || event.text == Key.LeftArrow {
                input.text = "";
                LauncherState.hide();
                return accept;
            } else if event.modifiers.control && (event.text == "j" || event.text == "l") {
                select-next();
            } else if event.modifiers.control && (event.text == "k" || event.text == "h") {
                select-previous();
            }
            reject
        }
    }
}
