import { VerticalBox, LineEdit } from "std-widgets.slint";
import { LauncherState } from "state.slint";
import { LauncherInput } from "input.slint";

// Re-export state singleton to make it accessible from rust
export {LauncherState} from "state.slint";


component Option inherits Rectangle {
    in property <string> name;
    in property <int> index;

    width: 100%;
    height: 50px;
    border-radius: 8px;

    background: touch.pressed ? #6b8282 : (index == LauncherState.selected_index) ? #6c616c : #456;

    animate background { duration: 100ms; }

    Text {
        text: name;
    }

    touch := TouchArea {
        changed has-hover => {
            if self.has-hover {
                LauncherState.selected_index = index;
            }
        }

        clicked => LauncherState.run_command(name);
    }
}

component Divider inherits Rectangle {
    width: 100%;
    height: 1px;
    background: #888;
}

export component Launcher inherits Window {
    title: "MiniLauncher";
    VerticalBox {
        LauncherInput { }

        Divider { }

        for entry[index] in LauncherState.entries: Option {
            name: entry.name;
            index: index;
        }
    }
}
