import { VerticalBox, LineEdit } from "std-widgets.slint";
import { LauncherState } from "state.slint";
import { LauncherInput } from "input.slint";
import { LauncherColors } from "colors.slint";
import { Mode, LauncherConfig } from "config.slint";
import { Option } from "option.slint";

// Re-export global singletons to make them accessible from rust
export { LauncherState } from "state.slint";
export { LauncherColors } from "colors.slint";
export { LauncherConfig } from "config.slint";

component Divider inherits Rectangle {
    width: 100%;
    height: 1px;
    border-radius: 1px;
    background: LauncherColors.border;
}

export component Launcher inherits Window {
    title: "MiniLauncher";
    background: LauncherColors.background;

    default-font-family: LauncherConfig.font-family;
    default-font-size: LauncherConfig.font-size;

    VerticalLayout {
        padding: LauncherConfig.padding;
        spacing: LauncherConfig.padding;

        LauncherInput { }

        Divider { }

        // Icon-only mode
        if LauncherConfig.mode == Mode.icons: HorizontalLayout {
            spacing: LauncherConfig.padding;
            for entry[index] in LauncherState.entries: LargeIcon {
                name: entry.name;
                index: index;
                icon: entry.icon;
            }
        }

        // Other modes (lines)
        if LauncherConfig.mode != Mode.icons: VerticalLayout {
            spacing: LauncherConfig.padding;
            for entry[index] in LauncherState.entries: Option {
                name: entry.name;
                index: index;
                icon: entry.icon;
                comment: entry.comment;
            }
        }
    }
}
