// Launcher global state

// Entry displayed in the menu
export struct LauncherEntry {
    name: string,
    icon: string, // "" if no icon
    description: string,
}

// Global app state
export global LauncherState {
    in-out property <[LauncherEntry]> entries;
    in-out property <int> selected_index: 0;
    callback update_entries(input: string);
    callback run_command(name: string);
    callback is_alphanumeric(c: string) -> bool; // needed for proper placeholder handling
}

// Color scheme (default = catppuccin mocha)
export global LauncherColors {
    in-out property <color> background: #1e1e2e;
    in-out property <color> text: #cdd6f4;
    in-out property <color> border: #45475a;    // surface1
    in-out property <color> accent: #cba6f7;    // mauve
    in-out property <color> highlight: #9399b2; // overlay2
}
